- id: bing_xiang_open_automation
  alias: 冰箱已打开
  description: 冰箱门打开提醒 + 飞书通知
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.bing_xiang_men_chuan_gan_qi
      from: "off"
      to: "on"
      for:
        seconds: 10

  action:
    # 🗣️ 第一步：冰箱门打开提示
    - device_id: 2c860e3b2531c3a912998507ceb7c400
      domain: text
      entity_id: 23433649854710410e2206d0287850fe
      type: set_value
      value: 冰箱门已打开

    # 🕒 第二步：等待1分钟内是否关闭
    - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.bing_xiang_men_chuan_gan_qi
          from: "on"
          to: "off"
      timeout: "00:01:00"
      continue_on_timeout: true

    # ✅ 如果关闭了
    - if:
        - condition: state
          entity_id: binary_sensor.bing_xiang_men_chuan_gan_qi
          state: "off"
      then:
        - device_id: 2c860e3b2531c3a912998507ceb7c400
          domain: text
          entity_id: 23433649854710410e2206d0287850fe
          type: set_value
          value: 冰箱门已关闭
      else:
        # 🚨 第三步：未关闭时重复提醒
        - repeat:
            count: 3
            sequence:
              - condition: state
                entity_id: binary_sensor.bing_xiang_men_chuan_gan_qi
                state: "on"
              - device_id: 2c860e3b2531c3a912998507ceb7c400
                domain: text
                entity_id: 23433649854710410e2206d0287850fe
                type: set_value
                value: 没有关闭冰箱门
              - service: rest_command.feishu_webhook1
                data:
                  message: >
                    🚨 冰箱门未关闭！
                    当前状态：{{ states('binary_sensor.bing_xiang_men_chuan_gan_qi') }}
              - service: notify.notify
                data:
                  message: 🚨 冰箱门未关闭！
                  title: 智能家居
                  data: {}
              - service: alarm_control_panel.alarm_trigger
                target:
                  entity_id: alarm_control_panel.gong_hua_jia_yuan_jian_kong_mian_ban
                data: { }
              - delay:
                  hours: 0
                  minutes: 2
                  seconds: 10
                  milliseconds: 0

- id: auto_reload_ha1
  alias: "重启HA"
  description: ""
  mode: single
  triggers:
    - trigger: time_pattern
      minutes: "1"
      seconds: "1"
  conditions:
    - condition: state
      entity_id: light.cozylife_smart_light
      state:
        - unavailable
      for:
        hours: 0
        minutes: 1
        seconds: 0
  actions:
    - action: homeassistant.restart
      metadata: { }
      data: { }

- id: desk_person_exists
  alias: "卧室电脑桌检测到有人"
  description: "卧室电脑桌检测到有人"
  mode: single
  triggers:
    - trigger: state
      entity_id:
        - binary_sensor.dian_nao_zhuo_ren_ti_cun_zai_chuan_gan_qi
      for:
        hours: 0
        minutes: 0
        seconds: 12
      from:
        - unknown
        - "off"
        - unavailable
      to:
        - "on"
  conditions: []
  actions:
    - if:
        - condition: state
          entity_id: switch.ssx_hass_deskclockswitch_attr_unique_id
          state:
            - "off"
          for:
            hours: 0
            minutes: 0
            seconds: 5
      then:
        - action: switch.turn_on
          metadata: {}
          target:
            entity_id: switch.ssx_hass_deskclockswitch_attr_unique_id
          data: {}
    - if:
        - condition: state
          entity_id: switch.ssx_hass_n2screenswitch_attr_unique_id
          state:
            - "off"
          for:
            hours: 0
            minutes: 0
            seconds: 5
      then:
        - action: switch.turn_on
          metadata: {}
          target:
            entity_id: switch.ssx_hass_n2screenswitch_attr_unique_id
          data: {}
    - repeat:
        count: 3
        sequence:
          - action: notify.ssx_cust_notify
            data:
              message: "{\"message\":\"欢迎\",\"emoji\":\"1f44b\"}"
              title: message_type
          - delay:
              hours: 0
              minutes: 0
              seconds: 1
              milliseconds: 0



- id: desk_person_not_exists
  alias: "卧室电脑桌检测到无人"
  description: "卧室电脑桌检测到无人"
  mode: single
  triggers:
    - trigger: state
      entity_id:
        - binary_sensor.dian_nao_zhuo_ren_ti_cun_zai_chuan_gan_qi
      for:
        hours: 0
        minutes: 0
        seconds: 12
      from:
        - unknown
        - "on"
        - unavailable
      to:
        - "off"
  conditions: []
  actions:
    - if:
        - condition: state
          entity_id: switch.ssx_hass_deskclockswitch_attr_unique_id
          state:
            - "on"
          for:
            hours: 0
            minutes: 0
            seconds: 5
      then:
        - action: switch.turn_off
          metadata: {}
          target:
            entity_id: switch.ssx_hass_deskclockswitch_attr_unique_id
          data: {}
    - if:
        - condition: state
          entity_id: switch.ssx_hass_n2screenswitch_attr_unique_id
          state:
            - "on"
          for:
            hours: 0
            minutes: 0
            seconds: 5
      then:
        - action: switch.turn_off
          metadata: {}
          target:
            entity_id: switch.ssx_hass_n2screenswitch_attr_unique_id
          data: {}
    - repeat:
        count: 3
        sequence:
          - action: notify.ssx_cust_notify
            data:
              message: "{\"message\":\"再见\",\"emoji\":\"1f4a4\"}"
              title: message_type
          - delay:
              hours: 0
              minutes: 0
              seconds: 1
              milliseconds: 0