# run with node102
# cat /config/configuration.yaml
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

#开启rest服务调用
api:

# Text to speech
tts:
  - platform: edge_tts # git@github.com:hasscc/hass-edge-tts.git
    service_name: xiaomo_say # service: tts.xiaomo_say
    language: zh-CN-XiaoxiaoNeural
    volume: +10%


#拼多多购买的cozylife灯泡和插座 git@github.com:shenshuxin01/hass_cozylife_local_pull.git
hass_cozylife_local_pull:

#自定义ssx插件
ssx_hass:

#小米米家
xiaomi_miot:

# Example configuration.yaml entry
logger:
  default: error
  logs:
    custom_components.ssx_hass: info
    custom_components.hass_cozylife_local_pull: warn

#2024-08-23 22:56:10.207 ERROR (MainThread) [homeassistant.components.http.forwarded] Received X-Forwarded-For header from an untrusted proxy 10.234.68.166
# 配置nginx代理
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.0.0/24

homeassistant:
  media_dirs:
    media: /config/media

rest_command:
  feishu_webhook1:
    url: "https://open.feishu.cn/open-apis/bot/v2/hook/389b6cdf-cfc7-4306-86a0-9dab97a44ff7"
    method: post
    payload: >
      { "msg_type": "text", "content": { "text": "{{ message }}" } }
    content_type: "application/json"

# 自动化配置
automation: !include automations.yaml