# cat /config/configuration.yaml
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

#开启rest服务调用
api:

# Text to speech
tts:
  - platform: edge_tts
    service_name: xiaomo_say # service: tts.xiaomo_say
    language: zh-CN-XiaoxiaoNeural
    volume: +10%


automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#拼多多购买的cozylife灯泡和插座
hass_cozylife_local_pull:

#自定义ssx插件
example_load_platform:

# Example configuration.yaml entry
alarm_control_panel:
  - platform: template
    panels:
      safe_alarm_panel:
        value_template: "{{ states('alarm_control_panel.example_load_platform_Node12AlarmControlPanelDeviceUnique') }}"
#        value_template: "{{ state_attr('alarm_control_panel.example_load_platform_Node12AlarmControlPanelDeviceUnique','ssx_diy') }}"
        arm_away:
          service: alarm_control_panel.alarm_arm_away
          target:
            entity_id: alarm_control_panel.example_load_platform_Node12AlarmControlPanelDeviceUnique
          data:
            code: !secret alarm_code
        arm_home:
          service: alarm_control_panel.alarm_arm_home
          target:
            entity_id: alarm_control_panel.example_load_platform_Node12AlarmControlPanelDeviceUnique
          data:
            code: !secret alarm_code
        disarm:
          - service: alarm_control_panel.alarm_disarm
            target:
              entity_id: alarm_control_panel.example_load_platform_Node12AlarmControlPanelDeviceUnique
            data:
              code: !secret alarm_code

# Example configuration.yaml entry
logger:
  default: info
  logs:
    custom_components.example_load_platform: info
    custom_components.hass_cozylife_local_pull: info

# Example configuration.yaml entry
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.0.101
