# cat /config/configuration.yaml
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

#开启rest服务调用
api:

# Text to speech
tts:
  - platform: edge_tts # git@github.com:hasscc/hass-edge-tts.git
    service_name: xiaomo_say # service: tts.xiaomo_say
    language: zh-CN-XiaoxiaoNeural
    volume: +10%


automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#拼多多购买的cozylife灯泡和插座
hass_cozylife_local_pull:

#自定义ssx插件
example_load_platform:

# Example configuration.yaml entry
logger:
  default: error
  logs:
    custom_components.example_load_platform: info
    custom_components.hass_cozylife_local_pull: warn

# 配置nginx代理
#http:
#  use_x_forwarded_for: true
#  trusted_proxies:
#    - 192.168.0.109

#当您从这些网络之一登录时，系统会询问您使用哪个用户帐户，并且不需要输入密码。如果开启此项，那么非下面的ip就不能访问啦，其他的验证方式也都失效
#homeassistant:
#  auth_providers:
#    - type: trusted_networks
#      trusted_networks:
#        - 10.234.104.88
#      allow_bypass_login: true

homeassistant:
  media_dirs:
    media: /media