# run with node102
# cat /config/configuration.yaml
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

#开启rest服务调用
api:

# Text to speech
tts:
  - platform: edge_tts # git@github.com:hasscc/hass-edge-tts.git
    service_name: xiaomo_say # service: tts.xiaomo_say
    language: zh-CN-XiaoxiaoNeural
    volume: +10%


#拼多多购买的cozylife灯泡和插座 git@github.com:shenshuxin01/hass_cozylife_local_pull.git
hass_cozylife_local_pull:

#自定义ssx插件
ssx_hass:

#小米米家
xiaomi_miot:

# Example configuration.yaml entry
logger:
  default: error
  logs:
    custom_components.ssx_hass: info
    custom_components.hass_cozylife_local_pull: warn

#2024-08-23 22:56:10.207 ERROR (MainThread) [homeassistant.components.http.forwarded] Received X-Forwarded-For header from an untrusted proxy 10.234.68.166
# 配置nginx代理
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.0.0/24

homeassistant:
  media_dirs:
    media: /config/media


# 自动化配置
automation:
  - alias: 冰箱已打开
    description: 冰箱已打开1
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.bing_xiang_men_chuan_gan_qi
        from: "off"
        to: "on"
    condition: []
    action:
      - device_id: 2c860e3b2531c3a912998507ceb7c400
        domain: text
        entity_id: 23433649854710410e2206d0287850fe
        type: set_value
        value: 冰箱已打开
    mode: single

  - alias: 冰箱已关闭
    description: 冰箱已关闭1
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.bing_xiang_men_chuan_gan_qi
        from: "on"
        to: "off"
    condition: []
    action:
      - device_id: 2c860e3b2531c3a912998507ceb7c400
        domain: text
        entity_id: 23433649854710410e2206d0287850fe
        type: set_value
        value: 冰箱已关闭
    mode: single